/**
 * Analytics constants from the Primo host application.
 * These const maps provide consistent event/page naming for analytics tracking.
 * Remotes should use these constants when firing analytics events to ensure
 * consistency with the host application's analytics pipeline.
 */

import { IgnoreMapSimpleString } from './search.model';

export const EventsNames = {
  NAVIGATE_MAIN_MENU: 'Main Menu Links',
  SIGN_IN: 'Sign In',
  SIGN_OUT: 'Sign Out',
  DISPLAY_FULL_RECORD: 'Display Full Record',
  ONLINE_RESOURCE_LINK: 'Online Resource Link',
  ADDITIONAL_LINKS: 'Additional Links',
  SORT: 'Sort',
  CREATE_PHYSICAL_REQUEST: 'Create Physical Request',
  CREATE_REQUEST: 'Create Request',
  EXPAND_RESULTS: 'Expand Results',
  FRBR_LINK: 'FRBR Link',
  USER_MENU_LINKS: 'User Menu Links',
  SAVED_RECORDS_ACTIONS: 'Saved Records Actions',
  LATERAL_LINKS: 'Lateral Links',
  CHANGE_LANGUAGE: 'Change Language',
  PAGINATION: 'Pagination',
  FACETS_USAGE: 'Facets Usage',
  SEARCH: 'Search',
  LOANS_PAGE_ACTIONS: 'Loans Page Actions',
  RENEW_LOANS: 'Renew Loans',
  SETTINGS: 'Settings',
  BANNER: 'Banner Actions',
  RESOURCE_RECOMMENDER_ACTIONS: 'Resource Recommender Actions',
  QR_CODE: 'QR Code',
  REQUESTS_PAGE_ACTIONS: 'Requests Page Actions',
  SET_PERSISTENT_FACETS: 'Set Persistent Facets',
  SEARCH_HISTORY_ACTIONS: 'Search History Actions',
  SAVE_QUERY: 'Save Query',
  FINE_AND_FEES_ACTIONS: 'Fine & Fees Actions',
  SAVED_SEARCHES_ACTIONS: 'Saved Searches Actions',
  USER_DASHBOARD_ACTIONS: 'User Dashboard Actions',
  BX_RECOMMENDATIONS: 'BX Recommendations',
  VIRTUAL_BROWSE: 'Virtual Browse',
  HOME_PAGE_NAVIGATION: 'Home Page Navigation',
  HYPER_TEXT_LINKING: 'Lateral Links',
  COLLECTION_DISCOVERY_ACTIONS: 'Collection Discovery Actions',
  SU_RECOMMENDATIONS: 'Syndetics Recommendations',
  CITATION_TRAILS: 'Citation Trail',
  RESEARCH_ASSISTANT_ANALYTICS_ACTION: 'Research Assistant Actions',
  RECORD_ACTIONS: 'Record Actions',
  PLACES: 'Places',
  CONSORTIA_SERVICES: 'Consortia Services',
  lINKED_DATA_ACTIONS: 'Entity Pages',
  TIMES_CITED: 'External Citation Providers',
  REPORT_A_PROBLEM: 'Report a Problem',
  RAPIDO_LINKS: 'Rapido Links',
  RAPIDO_CREATE_REQUEST: 'Create Request By Rapido',
  RAPIDO_SELF_REGISTRATION: 'Rapido Self Registration',
  PHYSICAL_LOCATION_ACTIONS: 'Physical Location Actions',
  DISPLAY_DIGITAL_VERSION_IN_EMBEDDED_VIEWER: 'Display Digital Version in Embedded Viewer',
  BOOK_CHAPTERS_AND_REVIEWS: 'Book Chapters and Reviews',
  MAY_ALSO_BE_HELD_BY: 'May Also be Held by',
  SIMILAR_IMAGE_BROWSE: 'Similar Image Browse',
  CITATION_LINKER: 'Citation Linker'
} as const;

export const PageNames: IgnoreMapSimpleString = {
  'home': 'Home Page',
  'search': 'Search Page',
  'jsearch': 'journal Search',
  'npsearch': 'Newspaper Search',
  'jfulldisplay': 'Journal Full Display',
  'npfulldisplay': 'Newspaper Full Display',
  'dbsearch': 'Database Search',
  'dbfulldisplay': 'Database Full Display',
  'researcherAssistant': '???',
  'researchAssistant': 'CDI Research Assistance',
  'collectionDiscovery': 'Collection Discovery',
  'openurl': 'Services Page (openurl)',
  'viewitopenurl': 'View Online Openurl',
  'fulldisplay': 'Full Display',
  'legantogetit': 'Leganto Get It',
  'favorites': 'Favorites Page',
  'tags': 'Tags Page',
  'person': 'Person Page',
  'account': 'My Library Card',
  'blankIll': 'Blank ILL request',
  'purchaseRequest': 'Blank Purchase Request',
  'deposit': 'Deposit',
  'delivery': 'Controlled Digital Lending',
  'login': 'Log In',
  'citationTrails': 'Citation Trail',
  'sourceRecord': 'Source Record',
  'citationlinker': 'Citation Linker',
  'chapters': 'Chapters Page',
  'model': '???',
  'browse': 'Browse Page',
  'orgList': 'Browse Research Units',
  'authsearch': 'Authority Search'
};

export const SearchTypes = {
  'FACETSEARCH': 'facetSearch',
} as const;
